### PR TITLE
add label prop for debugging

### PR DESCRIPTION
**Pull request by glennsl**

### CODE REVIEW

**Comment by cullophid** [comment]
I'm not sure I get the idea?

**Comment by cullophid** [comment]
I'm not sure I get the idea?

**Comment by glennsl** [comment]
It's a special property that gets added  to the css class geenrated by glamor. See https://github.com/paypal/glamorous/issues/242

**Comment by cullophid** [comment]
Ah. Awesome. I have had this issue quite a bit

**Pull request merged**
