### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mobily**
Hey @cullophid, I would like to add some new functions (for example `fontFace`), but first I think we need to clean up in this repo. 

This PR updates dependencies to the latest versions ~~and formats all reason files using the latest version of refmt~~.

### CODE REVIEW

**Comment by cullophid** [comment]
Hi Thanks for the dependency updates!
refmt is disabled on purpose, so please do a PR without it :)

**Comment by mobily** [comment]
@cullophid I'm wondering, is there any reason why it's disabled? I think using `refmt` is beneficial to all contributors and it standardizes the code written by the developers

**Comment by cullophid** [comment]
Yes there are a few.
I think refmt/prettier/etc. are great tools!
I use them frequently when ever i have large blocks of code with botched formatting. e.g.
Having said that I generally don't find that these tools improve the code. Actually i find that in some edge cases they can make it slightly less readable.

I dont care too much how developers (either my employees or OSS contributors) format the code as long as its still easy to read. Some things have a big impact:
```
let user = {
  name: "Andreas",
  email: "andreas@sentia.ai"
};
let user =
 { name= "Andreas"
  , email= "andreas@sentia.ai"
  }
```
others are completely irrelevant:
```
let id = (v) => v;
let id = v => v;
```

I do care that developers are mindful about how their codes conveys the message they want to tell. formatting can be a tool for this (not the most important one but still a tool).

I would love it if refmt had an option to only format the lines that you just changed. then people who wanted to use it could, but it would not be forced on anyone else. Sadly to my knowlege this is not possible.

**Comment by cullophid** [comment]
I am also seeing a worrying trend forming around formatting tools. I see a lot of developers argue that by using formatters we dont have to argue about formatting any more.

We never actually had to argue about formatting. We could have just accepted that people write code in slightly different ways. As long as the differences do not have significant negative impact on the code just let it go.

It seems to me that often formatters are not a way for teams to agree on formatting, but for individuals to force their preference on the whole team.

Trying to solve people problems with a code tool is a really bad idea!

**Comment by mobily** [comment]
> leave out refmt

sure, will do that later today :ok_hand:

I decided to use it because there are few places where the code looks incoherent. 

In general, I agree with what you just said, but on the other hand, I think in the project like this, where there are contributors with the different coding style, the tool like refmt/prettier/whatever might be helpful. Arguing about the formatting style is merely waste of time.

Anyway, thank you for more clarification about that 😉

**Comment by mobily** [comment]
@cullophid ✔️ done :)

**Comment by cullophid** [comment]
Thanks!!

**Comment by mobily** [comment]
thank you! 🎉

**Pull request merged**
