### PR TITLE
add a missing list-style prop

### PR DESCRIPTION
**Pull request by knowbody**
there's a missing "none" prop that removes bullets from the list

I'm not sure about the formatting of the files, but it seems like refmt formatted both `Css.re` and `Css.rei`

### CODE REVIEW

**Comment by cullophid** [comment]
please submit a version without the formatting changes

**Comment by knowbody** [comment]
Sure I will do that in a minute. Do you want me to send the PR with the
formatted code separately? This is the new formatting that refmt does

**Comment by cullophid** [comment]
No im not using refmt :)

**Comment by mobily** [comment]
@knowbody the discussion about refmt is here: https://github.com/SentiaAnalytics/bs-css/pull/38#issuecomment-374548627 😉

**Comment by knowbody** [comment]
done

**Comment by cullophid** [comment]
Thanks!

**Pull request merged**
