### PR TITLE
Filter property

### PR DESCRIPTION
**Pull request by JakubMarkiewicz**
Hey, I've added filter property + tests.
Not related to any issue, needed it for my own purpose.
```ocaml
type filter = [
  | `blur(length)
  | `brightness(float)
  | `contrast(float)
  | `dropShadow(length, length, length, color)
  | `grayscale(float)
  | `hueRotate(angle)
  | `invert(float)
  | `opacity(float)
  | `saturate(float)
  | `sepia(float)
];
```

### CODE REVIEW

**Comment by giraud** [comment]
wow tests 😍 thanks !

**Comment by giraud** [comment]
filter is defined as a list of `filter_function | url` ... can you change the def to accept an url ?
also missing `none | inherit | initial | unset`
it would be great if you don't mind adding them to the pr

**Comment by JakubMarkiewicz** [comment]
Sure thing, will add them later today.

**Comment by JakubMarkiewicz** [comment]
```ocaml
type filter = [
  | `blur(length)
  | `brightness(float)
  | `contrast(float)
  | `dropShadow(length, length, length, color)
  | `grayscale(float)
  | `hueRotate(angle)
  | `invert(float)
  | `opacity(float)
  | `saturate(float)
  | `sepia(float)
  | `url(string)
  | `none
  | cascading
];
```

**Pull request merged**
