### PR TITLE
Added open Css; to the top of the example

### PR DESCRIPTION
**Pull request by Aleksion**
So I'm completely new to both OCaml and Reason, so I might just have completely misunderstood something.
But I couldn't get the sample to work, because my project couldn't find style or backgroundColor (etc.). I found at that if I accessed them in the module (as is done in the example in the example folder) everything works as expected.

I don't know what's considered good or bad practice yet, but I like the idea of opening the Css module at the top to make it easier to access all the styling properties. 

I'm sorry if I've misunderstood something! :)

### CODE REVIEW

**Comment by Ebuall** [comment]
I think open has to be inside the module, so it doesn't pollute global namespace.
I even have snippet for this:
```reason
module Styles = {
  open Css;
  /* ... */
};
```

**Comment by Aleksion** [comment]
arhh, that makes sense! I'll update it accordingly

**Comment by cullophid** [comment]
Hi Thanks for that... welcome to ReasonML!
If you haven't already make sure to join the discord channel... it can be a little tough  to get started without help :)

**Comment by Aleksion** [comment]
Thank you! I look forward to diving more into ReasonML

**Pull request merged**
