### PR TITLE
Proposal for padding and margin shorthands

### PR DESCRIPTION
**Pull request by glennsl**

### CODE REVIEW

**Comment by wyze** [comment]
Yes, just ran into specifying `padding: 4em 6em` into all 4 props. This would be super useful.

**Comment by cullophid** [comment]
Can you rebase so we dont get all the formatting changes

**Comment by glennsl** [comment]
Done. FOr some reason I had to rebase each PR twice, which was incerdibly annoying, but I hope it goes smoothly now. If not, just approve the PRs that look good, then I can rebase and merge them myself.

**Comment by cullophid** [comment]
I'm not too sure about this margin2 is not a great api. We could use marginTopBottom, and marginLeftRight

**Comment by cullophid** [comment]
margin3 and 4 I don't think add that much value

**Comment by glennsl** [comment]
I don't know what `marginTopBottom` and `marginLeftRight` refers to.

Note that the arguments are labeled, and therefore not ambiguous. They could be more verbosely labeled of course, but this should be obvious to anyone that know css shorthands I think. And familiarity seems like a good measure.

I use `margin3` fairly often. `margin4` not so much. But I don't really see the harm in including them unless shorthands in general are excluded.

**Pull request merged**
