### PR TITLE
rewrite of bs-css

### PR DESCRIPTION
**Pull request by cullophid**
Complete rewrite of bs-css.

**New types**
we are now using polymorphic variants

```
let margin : [ `auto | length ] => rule;

```

this allows us to make shortcuts for  common values:

```
let style = Css.(style([
  display(flex),
  flexDirection(row),
  alignItems(stretch),
  justifyContent(spaceBetween),
  margin(auto),
]));

```

there are shortcuts for all values except incases where values collide with propertyNames e.g. `left`

**Style now returns a string**

the style function now returns an actual string.
this means that you can no longer use merge on styles.
instead simply merge lists of styles..

```
  let someStyle = Css.(style([ background(red), ...defaultStyle]);
```

**Css rule priority reversed**

since we are now using lists to merge styles, the priority is reversed to fit better with reason lists

```
  let defaultStyle = Css.(style([color(red)]));
  let someStyle = Css.(style([color(black), ...defaultStyle])); /* Color will be black*/

```

### CODE REVIEW

**Comment by cullophid** [comment]
@glennsl @chenglou I would love to hear if you have any comments on this before i merge....

**Comment by chenglou** [comment]
No opinon =)

**Comment by glennsl** [comment]
Implementation-wise, compared to using using abstract types, it looks like this will have a bit more of a performance overhead due to all the branching, and will be more bloated and harder to minify with tree shaking, also because of branching (or rather centralization) but also a fair bit of duplication. There's no giant switch though, which is good and seems to strike the right balance for this approach.

The primary benefit seems to be an easier to understand type that deals better with some of the edge-cases I've been dealing with, but there's quite a few issues here too.

Some observations:
- Not all values have functions that hide the polymorphic variant, and there's no clear distinction for when to use one or the other. I suppose you could always use the polymorphic vairant, but as it is it seems a bit inconsistent.
- The universal values, `inherit`, `unset` and `initial` are absent.
- Many properties only support a subset of the values they should, like `fontWeight` which takes an int, but should accept several different keywords as well (and should only accept a tiny subset of valid integers, 100, 200 etc. 101 is not valid). Or `flexBasis` which also takes an int here but should accept any length, percentage or a number of keywords.
- The `flex` shorthand property is missing. It's an annoyingly clever shorthand property that is not easy to "deconstruct". `flex: 1` can't just be translated to `flexGrow(1)`, for example. You have to know what this would set the other properties to as well. For that reason, using `flex` rather than the individual rpoeprties is actually recommended and what you'll mostly see in the wild.
- There's no way to set multiple `transition`s, `animation`s or `boxShadow`s. Figuring out a good API for these is an interesting challenge.
- There's many small variations that are not properly covered. Lots of properties that should accept `none`, `outlineColor` should accept `invert`, `alignSelf` should accept `auto`, `justifyContent` should _not_ accept `stretch` etc.
- There's no `content` property. That's also an interesting one.

I suspect you know most of this of course, since they're mostly the result of the central trade-off to the approach. Lots of this could certainly be fixed, but at the cost of significantly more code.

The list spread approach is interesting, but I'm not sure it's worth the priority reversal. It seems really weird to have to order everything upside down, and need to switch between them in normal css vs bs-css. For example, I often override a property to be able to quickly a/b test it, e.g.
```
color: red;
color: blue;
```
Or having to put a hover selector above another selector with the same specificity to be able to override it.

My solution to this in typed-glamor has been to use an `add` function instead:
```
let add: list(declaration) => declaration;
```

Hope this help! And let mw know if I've misunderstood something. I'd really like to understand the nuances of this approach too.

**Comment by cullophid** [comment]
@glennsl 
1. the problem is name collision. I would have to either change the name of the value or the property function
2. the universal values are left out intentionally, I dont think they make sense in modular css / css-in-js, since you dont use the cascade. This same reasoning applies to things like `bolder/lighter` for font-weight.
3. I have removed duplicate values... so you can only specify one thing one way. fontWeight is one example. I think the new api is more intuitive than `_100`.
4. I agree with this one. 
5. you can set multiple transitions using `transitions([rotate(...), skew(...)])`, this model does not quite work for shadows and animations though... I dont know how best to solve this atm.
6. true, its not 100% up to spec, but neither is the current version, so Im ok with these things happening after merge.
7. I dont think we need a content property, It seems to me that its not usable in this context.

**Comment by cullophid** [comment]
The solution is less performant than your proposed one, but the types are simpler.
This means tooling/ error output will be much simpler to understand.

Im not myself sure about the list spread, but I wanted to fix the issue with typing the css rules as string. It seems to me that the most common use case is adding custom overwrites to a predefined style ```
let fanzyButton = [
  color(hotPink),
 ...button
];
<button className=style([background(darkGray), ...fanzyButton]) >
```

in this case reversing the order makes sense. it should also be more performant.

while I do think performance is important, i think the best approach will be to predefine styles, and overwrite with the styleprop at runtime. 
```
let fanzyButton = style([
  color(hotPink),
  ...button
]);

let make = (~onClick, _) => {
 ...component,
 render: (_) => 
  <button className=fanzyButton style=(React.style(~backgroundColor("darkgray")) onClick />
}
```

**Comment by cullophid** [comment]
I wanted to make a className function and a style function separate, but then ReasonReact changed the style prop api :(

**Comment by cullophid** [comment]
I dont think we need everything. just everything you need :)

**Comment by cullophid** [comment]
I added a simple version of flex that just accepts a number, this is not as power full as the css flex prop, but still provides the most common shorthand.

the value flex in display(flex) is now flexBox: display(flexBox),

**Comment by glennsl** [comment]
Just to quickly reply to your responses above:


> 1. the problem is name collision. I would have to either change the name of the value or the property function
Right, that makes sense and is as good a solution as any I cant hink of.

> 2. the universal values are left out intentionally, I dont think they make sense in modular css / css-in-js, since you dont use the cascade. This same reasoning applies to things like bolder/lighter for font-weight.
You use cascading in css-in-js too. A lot. Otherwise you mgiht as well remove `selector`, `hover`, `media` etc. too. These can also be sueful when merging objects (which you've jsut prposed to achieve by reversing the entire order of declarations). One example is having `display: none;` by default, then overriding that with `unset` or `initial` when some condition applies.

> 3. have removed duplicate values... so you can only specify one thing one way. fontWeight is one example. I think the new api is more intuitive than _100.
I'm not so sure it's so intuitive that `100` is a vlaid value, but `150` is not. And not sure what the duplicate value for `flexBasis: fill` is, for example.

> 5. you can set multiple transitions using transitions([rotate(...), skew(...)]), this model does not quite work for shadows and animations though... I dont know how best to solve this atm.
Those are transforms, not transitions. But transitions is much like animations and boxShadows.

> 7. I dont think we need a content property, It seems to me that its not usable in this context.
You don't always have full control over the dom. In redex, for example, I render markdown to HTML and insert it into the dom using `dangerouslyInsertInnerHTML`. And I still want to style it. I could fo course fall back to plain css, or `unsafe`, but it's certainly still usable.

> I added a simple version of flex that just accepts a number, this is not as power full as the css flex prop, but still provides the most common shorthand.
This is a good solution I think. Covers at least 80% of what you'd use `flex` for.

    true, its not 100% up to spec, but neither is the current version, so Im ok with these things happening after merge.
    I dont think we need a content property, It seems to me that its not usable in this context.

**Comment by cullophid** [comment]
You are right about transitions, ill add that the same way as boxShadows.

**Comment by cullophid** [comment]
My point about the cascade was more that default/values is only relevant if you don't know what explicit value to set. In that case you would be relying on the context the component gets mounted in to define its style... I don't think that's a good idea, and i think it defeats the purpose of defining the styles inside the component.


Does that make more sense?

**Comment by cullophid** [comment]
My main concern with initial/default values are that they screw up the api for several properties...

**Comment by cullophid** [comment]
Flex basis is all wrong ATM :)

**Comment by glennsl** [comment]
Yes, that makes more sense to me. Still not sure I agree though. It makes a lot of sense for me to be able to define generic media styles that can be applied to both flex, box and inline elements to hide or show them in certain conditions, for example. But of course it certainly isn't necessary, and is a big trade-off, especially with this approach.

**Comment by cullophid** [comment]
Let's just see if it comes up... If its a problem well fix it

**Pull request merged**
