### PR TITLE
Change all functions accepting unions of polyvariants to have upper boundaries

### PR DESCRIPTION
**Pull request by TomiS**
Relates to https://github.com/SentiaAnalytics/bs-css/issues/172

### CODE REVIEW

**Comment by TomiS** [comment]
Ok, I went on and changed all functions in Css.rei that I was able to identify. It still builds and seems to work correctly, so based on my limited knowledge it _should_ be fine.

This change allows me to define a theme like this and still use bs-css
```
type themePrint = {
  .
  "textColor": [ | `hex(string)],
  "baseFontSize": [ | `pt(int)],
  "baseMargin": [ | `pt(int)],
  "pageWidth": [ | `mm(float)],
  "pageHeight": [ | `mm(float)],
};
```

**Comment by giraud** [comment]
Thank you for that work, appreciate.

one thing I don't understand in your pr, is why you had to introduce all these utility functions, like lengthToString, colorToString, ....
Also, I don't understand why you had to transform simple types like borderBottomLeftRadius.

**Comment by TomiS** [comment]
With utility functions I followed the same pattern as with already existing `marginToString`. They are just there to make the code less verbose but can be of course replaced with the actual switch statement it that is seemed better. Personally I'd probably hide them inside an Utils module or something.

If you don't understand why I had to transform simple types, that makes two of us. :) I also found it a bit weird but if I didn't do it, compiler would error when using the upper boundary in `.rei` files. It just seemed to be a way to make compiler happy. I'm not aware if we are e.g. losing some type safety with that or what's going on but that was the only way I was able to make it work. Would be awesome if someone who actually understands ReasonML would explain this to me too.

**Comment by TomiS** [comment]
Oh, in case you're wondering, I did ask/discuss about using the upper boundary in general in ReasonML discord in bindings-to-libraries just few days ago where people more experienced than me told it would be the "more correct" way to type this kind of API. So I'm not just pulling this out of my sleeve :D

**Comment by giraud** [comment]
I understand ` <`  when signature is `[ | A | B ]` but not when it's only `A` .

**Comment by TomiS** [comment]
Yep, it compiles for some reason when one only adds the `<` in unions. Probably because they are already implemented with pattern matching `switch` statements. However, for a consistent behavior one needs to add them to the non-union versions too where there is only one type. Otherwise it won't behave correctly in those situations.

**Comment by giraud** [comment]
Hi, I've changed the signature of union types in master, so I close this pr.

**Comment by TomiS** [comment]
@giraud Nice job.

There's one problem though. I installed the master version and started getting this error in my code:
```
  19 ┆   getHeightWithFooter(dimensions, theme##print##footerHeight),
  20 ┆ ),
  21 ┆ paddingLeft(theme##print##pageMargin),
  22 ┆ paddingRight(theme##print##pageMargin),
  23 ┆ boxSizing(`borderBox),
  
  This has type:
    [ `mm(float) ]
  But somewhere wanted:
    Css.Types.Length.t
  The first variant type does not allow tag(s)
  `calc, `ch, `cm, `em, `ex, `inch, `pc, `percent, `pt, `px, `pxFloat, `rem,
  `vh, `vmax, `vmin, `vw, `zero
```
I think this happens because this signature is missing the upper boundary
https://github.com/SentiaAnalytics/bs-css/blob/master/src/Css.rei#L759

I'm pretty confident that, while being syntactically more ugly, it's necessary to add the upper boundary  also to the rest of the function signatures if one wants to achieve a consistent behavior. It's because e.g. `Css.Types.Length.t` is already a variant https://github.com/SentiaAnalytics/bs-css/blob/master/src/Css_AtomicTypes.rei#L51-L74, even if it's alone, not just a simple type.

**Comment by giraud** [comment]
@TomiS can you give me an exact code that doesn't compile ?

**Comment by TomiS** [comment]
@giraud I'll make a separate minimal test repository as soon as I've finished my current work thingy.

**Comment by TomiS** [comment]
@giraud Ok, here we go:
https://github.com/TomiS/bs-css-demo/tree/master/src

This repository should demonstrate the use case quite nicely, I hope. (check the comments in the beginning of the files). I checked it build with my fork but fails current with bs-css master.

**Comment by giraud** [comment]
@TomiS , answered in your repo.

**Comment by TomiS** [comment]
@giraud Wow, thanks. I need some time to let that sink in. I'll comment as soon as I have totally understood it.

**Pull request closed without merging**
