### PR TITLE
Upgrade to Emotion v10

### PR DESCRIPTION
**Pull request by simonkberg**
This upgrades to [emotion 10](https://github.com/emotion-js/emotion/blob/master/CHANGELOG.md#v1000-2018-10-27). The API is completely backwards compatible with the bindings in bs-css, but it's potentially a breaking change for downstream users. Integration with react, especially for SSR, is looking a bit differently.

I have confirmed the example project looks identical after the upgrade.

I also exposed Emotion's `cache` instance (as an abstract type), to enable integration with react and for SSR support. See ["Migrating to Emotion 10"](https://emotion.sh/docs/migrating-to-emotion-10) and ["Using Emotion 10 with the old SSR APIs"](https://emotion.sh/docs/ssr#using-emotion-10-with-the-old-ssr-apis).

### CODE REVIEW

**Comment by simonkberg** [comment]
> I chose emotion@9 a couple months back over 10 because it hadn't solidified yet.

Makes sense :+1: 

> The one thing I'm a bit leery about is what `cache` does for us?

It doesn't really do anything for bs-css, it's exposed purely for integration purposes. If you're using bs-css in a server rendered react app for example, you'll need to pass this cache instance to `CacheProvider` (from `@emotion/core`).

By default emotion (v10) assume you're using the new `@emotion/styled` or `@emotion/core` packages with react which uses a different cache instance, so the "vanilla" instance from the `emotion` package containing all our styles won't be picked up.

If we don't expose it, the only way to retrieve the correct cache instance would be to rely on package hoisting in npm/yarn which is unpredictable.

**Comment by giraud** [comment]
I'm ok to upgrade to emotion 10 if it's completely backward compatible.
And in that case, can we just change the version package.json to a more permissive range to not force users to upgrade to 10 ? somthing like: 
```
  "dependencies": {
    "emotion": ">=9 <=10"
  },
````

**Comment by giraud** [comment]
about the cache, is it just a temporary implementation for when people use the old api ? Does that mean our bindings are not pointing to the new API of emotion 10 ?

**Comment by simonkberg** [comment]
> I'm ok to upgrade to emotion 10 if it's completely backward compatible.

The "vanilla" APIs are backwards compatible, so if you're just using bs-css standalone in your project and don't integrate with any other emotion packages there should be no breaking changes.

> And in that case, can we just change the version package.json to a more permissive range to not force users to upgrade to 10 ? somthing like:
> 
>  ```
>   "dependencies": {
>     "emotion": ">=9 <=10"
>   },
> ```

That's not really how dependency ranges work. It would just install the latest version available on npm satisfying that range. Are you thinking of peer dependencies? That would require us not shipping emotion with the package (as a dependency), so everyone can install their own emotion version satisfying the peer dependencies range.

In any case this should be released as a major version.

> about the cache, is it just a temporary implementation for when people use the old api ? Does that mean our bindings are not pointing to the new API of emotion 10 ?

Not really, the "new" emotion APIs are react-specific, and I don't think bs-css should limit itself to just be compatible with react. The APIs we provide bindings for here are the "vanilla" APIs which has its own cache instance, so we expose it so you can integrate with the framework (react) specific APIs if needed.

cc @tkh44 @mitchellhamilton @andarist in case my thinking here is way off.

**Comment by giraud** [comment]
@simonkberg ok, then let's first release a new version with the small changes, and then do a major release with v10

**Comment by Andarist** [comment]
> Not really, the "new" emotion APIs are react-specific, and I don't think bs-css should limit itself to just be compatible with react. The APIs we provide bindings for here are the "vanilla" APIs which has its own cache instance, so we expose it so you can integrate with the framework (react) specific APIs if needed.

Hard to tell without diving more into what is being discussed here - but in general I think you understanding is correct. Emotion has framework-agnostic APIs but it has also API more integrated with react as well. It's somewhat quirky that there are 2 sets of APIs - but OTOH this allows for more things while using react and still provides framework-agnostic API, so 🤷‍♂️

**Pull request merged**
