### PR TITLE
Direction

### PR DESCRIPTION
**Pull request by JakubMarkiewicz**
Direction property + tests
Related to #131

### CODE REVIEW

**Comment by erykpiast** [comment]
Oh yeah! When this one is supposed to be merged? Do you need some help with testing?

**Comment by giraud** [comment]
I've been busy, sorry for the delay

**Comment by erykpiast** [comment]
Thank you so much @giraud! Would you like to publish v9 in the near future? :)

**Comment by giraud** [comment]
yep, next week seems good.

**Comment by erykpiast** [comment]
Wonderful!

**Comment by erykpiast** [comment]
@giraud what about publishing this week? :)

**Pull request merged**
