### PR TITLE
[RFC] Feature: Minimal Css Variable support

### PR DESCRIPTION
**Pull request by brad-decker**
First off, Thanks for this awesome library. I feel pretty passionate about helping out where I can here. I thought about creating an issue for this first, and I can definitely cross post there, but I wanted to get an example of what I think could work. There's probably a lot of work here or some things we shouldn't do. I am just getting started with Reason so I will be very gracious of any feedback on coding style, etc. 

Basically I am trying to currently build a theme system using css variables and i'd like to keep that really locked down inside of Reason by only supporting a set number of variables. I was planning on doing something like this in my code base:

```ocaml
type allowedColors =
  | Primary(Css.color)
  | Secondary(Css.color);

let setThemeColor = (variable) => {
  switch(variable) {
  | Primary(color) => Css.unsafe("--mdc-re-color-primary", string_of_color(color))
  | Secondary(color) => Css.unsafe("--mdc-re-color-secondary", string_of_color(color))
  };
};
```

to keep the variable names abstracted. The problem with doing this entirely in userland is that we don't have access to the helper methods inside the library for manipulating values. I had copy pasted them over but it seemed verbose and I was curious if something like this would make sense here.

### CODE REVIEW

**Comment by brad-decker** [comment]
Just realized that formatting changed everywhere. let met see if i can clean that up.

**Comment by brad-decker** [comment]
Would love some pointers on how to maintain the original formatting of this library. I noticed when I ran yarn yarn.lock was also updated with the latest version of bs-platform. Is this the source of the problem. Should I lock it into the previous version to keep this PR clean?

**Comment by brad-decker** [comment]
@giraud / @cullophid  I'll be rebasing this so it is at least somewhat reviewable and I can start collecting feedback :)

**Comment by giraud** [comment]
yes, please

**Pull request closed without merging**
